#!/usr/bin/env bash

service_name="${1?Service name is required}"
name="$(hostname | sed 's/nomad-cluster-[^-]*-//')"

journalctl -o cat -u "${service_name}" -f | mawk -W interactive "NAME=\"${name}\" {gsub(/^ +/, \"\"); printf \"%s %s\n\", NAME, \$0}" | mawk -W interactive "SRV=\"${service_name}\" {gsub(/^ +/, \"\"); printf \"<%s> %s\n\", SRV, \$0}"
