#!/usr/bin/env bash

service_name="${1?Service name is required}"

journalctl -o cat -u "${service_name}" -f | mawk -W interactive "PREPEND=\"$('hostname')\" {gsub(/^ +/, \"\"); printf \"%s %s\n\", PREPEND, \$0}"
